from utils_numeric import num
from ieee519 import tdd_limit
import re

def extract_number(value):
    """
    Safely extracts the first decimal or integer found in a string.
    Example: "800 KVA" -> 800.0, "4.9%" -> 4.9
    """
    if value is None:
        return None
    
    # Use regex to find the first number (including decimals)
    match = re.search(r'[-+]?\d*\.?\d+', str(value))
    if match:
        try:
            return float(match.group())
        except ValueError:
            return None
    return None

def Trasformer_Limits_Analysis(details, df, feeder, time_val, type_val):
    """
    Perform transformer engineering calculations
    using nameplate details + measured data.
    Returns None if the time_val row is not found in df,
    or if critical nameplate fields (rating_kva, voltage_level) are missing.
    """

    row = df[df["Time"] == time_val]

    if row.empty:
        return None

    row = row.iloc[0]

    # -----------------------------
    # Nameplate data — safe .get()
    # -----------------------------
    voltage_level = (details.get("voltage_level") or {})
    lv_raw        = voltage_level.get("lv") or ""
    hv_raw        = voltage_level.get("hv") or ""

    # FIXED: Look for the correct keys generated by main.py
    rating_raw    = details.get("rating")
    impedance_raw = details.get("impedance")
    vector_group  = details.get("vector_group") or ""

    # rating is critical — return None if missing
    # FIXED: Use extract_number to strip text like "KVA"
    rating = extract_number(rating_raw)
    if rating is None:
        return None

    # Parse LV  e.g. "433V" → 433 → 0.433 kV
    try:
        lv    = int(str(lv_raw).upper().replace("V", "").replace("KV", "").strip())
        lv_kv = lv / 1000 if lv > 100 else float(lv)   # handle both "433V" and "0.433kV"
    except (ValueError, ZeroDivisionError):
        lv_kv = 0.433   # safe fallback

    # Parse HV  e.g. "11kV" → "11"
    try:
        hv_num = str(hv_raw).upper().replace("KV", "").strip() or "?"
    except Exception:
        hv_num = "?"

    # Combined voltage rating string for display: "11/0.433"
    voltage_rating = f"{hv_num}/{lv_kv}"

    # -----------------------------
    # Full load current
    # -----------------------------
    full_load_amps = rating / (1.732 * lv_kv) if lv_kv else 0

    # -----------------------------
    # Measured current (max phase)
    # -----------------------------
    measured = max(
        num(row["A1ʀᴍꜱ"]),
        num(row["A2ʀᴍꜱ"]),
        num(row["A3ʀᴍꜱ"])
    )

    # -----------------------------
    # Short circuit current
    # -----------------------------
    # FIXED: Use extract_number to strip text like "%"
    impedance = extract_number(impedance_raw)
    if impedance:
        isc = round(full_load_amps * 100 / impedance, 2)
    else:
        isc = 0

    # -----------------------------
    # Return structured result
    # -----------------------------
    return {

        "Feeder_Name": feeder,
        "Type": type_val,

        "Transformer_Capacity_KVA": rating,
        "voltage_rate_kva": voltage_rating,

        "full_load_amps": round(full_load_amps, 2),

        "impedance_percent": impedance if impedance is not None else "",
        "vector_group": vector_group,

        "short_cirtuit_amps": isc,

        "Transformer_A": round(measured, 2),

        "Isc/IL": round(isc / measured, 2) if measured else 0,

        "lv_kv": lv_kv,
        "TDD": tdd_limit(isc / measured) if measured else tdd_limit(0),

        "Ithd": round(max(
            num(row["A1ᴛʜᴅf"]),
            num(row["A2ᴛʜᴅf"]),
            num(row["A3ᴛʜᴅf"])
        ), 2),
    }